// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVw2KFXwpEOUsCCkv85hp5RkGAu3S1y8k',
    appId: '1:722777072311:web:3d8ccd381a0bfee54ea332',
    messagingSenderId: '722777072311',
    projectId: 'st-akhir',
    authDomain: 'st-akhir.firebaseapp.com',
    storageBucket: 'st-akhir.appspot.com',
    measurementId: 'G-G4TWQZRNZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDanRKG3jbeHiA9SZAZD-9DkKdM3y3He08',
    appId: '1:722777072311:android:6f24f2b328b557c44ea332',
    messagingSenderId: '722777072311',
    projectId: 'st-akhir',
    storageBucket: 'st-akhir.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPrcQUPn-rBTFiVIauehsyWlpXeFnkyKE',
    appId: '1:722777072311:ios:62b2e9eaded5929b4ea332',
    messagingSenderId: '722777072311',
    projectId: 'st-akhir',
    storageBucket: 'st-akhir.appspot.com',
    iosBundleId: 'com.example.sobatternakApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPrcQUPn-rBTFiVIauehsyWlpXeFnkyKE',
    appId: '1:722777072311:ios:62b2e9eaded5929b4ea332',
    messagingSenderId: '722777072311',
    projectId: 'st-akhir',
    storageBucket: 'st-akhir.appspot.com',
    iosBundleId: 'com.example.sobatternakApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVw2KFXwpEOUsCCkv85hp5RkGAu3S1y8k',
    appId: '1:722777072311:web:c2f7750df838002d4ea332',
    messagingSenderId: '722777072311',
    projectId: 'st-akhir',
    authDomain: 'st-akhir.firebaseapp.com',
    storageBucket: 'st-akhir.appspot.com',
    measurementId: 'G-FW195ZKW5G',
  );
}
